services:
  web:
    image: mplibunao/kubernetes_node
    restart: always
    env_file:
      - .env
    ports:
      - "80:8080"
    networks:
      - app-network

  db:
    image: mongo:5.0.3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - db_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
